import { ThemeProvider } from '@/providers/ThemeProvider'
import type { Metadata } from 'next'

import './globals.css'

import { ReactQueryProvider } from '@/providers/ReactQueryProvider'
import { Navbar } from '@/components/shared'

export const metadata: Metadata = {
  title: 'Ecom nextjs/laravel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </ReactQueryProvider>
    </html>
  )
}
